server:
  servlet:
    context-path: /fei/biodisel/v1

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  oil:
    name: oilQueue
  decanter:
    name: decanterQueue
  reactor:
    name: reactorQueue
  naEt:
    name: naEtQueue